### ISSUE TITLE
【課題】220904

### ISSUE THREAD

**Issue by technicakidz** [Takamura-000/my-first-blog#4]
### TODO

- [ ] 次回簡易的なwebアプリを作るための streamlit 調査
   - このフレームワークはなにか？
   - 用途は？
   - どんな機能を実現できそうか？
→ この issue のコメントに記載する
- [ ] チュートリアル「テンプレート内の動的データ」まで
→ master push したものを確認します
- [ ] ポートフォリオサイト(修正完了状態)のURLを共有する
  - URLは `https://xxx.github.io` みたいなアレ

**Comment by technicakidz** [comment]
### ポートフォリオのカスタマイズ
#### TODO

- [ ] ヘッダー画像の差し替え
- [ ] 作品一覧(WORKS)の修正
- [ ] スキル(SKILL)を実態に即した内容にする
- [ ] 自己紹介文の修正
- [ ] 問い合わせ先の修正(ご自身でご判断ください)

**Comment by technicakidz** [comment]
今の状態を知りたいので上記の更新をよろしくお願いします！
